TrainTicket/Controllers/StationsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TrainTicket.Data;
using TrainTicket.Models;

namespace TrainTicket.Controllers
{
    public class StationsController : Controller
    {
        private readonly DataContext _context;


        public StationsController(DataContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {

            if (HttpContext.Session.GetString("Email") == null)
            {
                return RedirectToAction("NotFound", "Home");
                
            }
            if (HttpContext.Session.GetString("UserType") == "Admin" || HttpContext.Session.GetString("UserType") == "Seller")
            {
                var totalStation = _context.stations.Count();
                ViewBag.totalStation = totalStation;
                var stations = _context.stations.ToList();
                return View(stations);
            }
            return RedirectToAction("NotFound", "Home");
        }
        public IActionResult Create()
        {
            if (HttpContext.Session.GetString("Email") == null)
            {
                return RedirectToAction("NotFound", "Home");
                
            }
            if (HttpContext.Session.GetString("UserType") == "Admin" || HttpContext.Session.GetString("UserType") == "Seller")
            {
                return View();
            }
            return RedirectToAction("NotFound", "Home");
        }
        [HttpPost]
        public IActionResult Create(Station station)
        {
            _context.Add(station);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }









    }
}

TrainTicket/Controllers/TicketController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TrainTicket.Data;
using TrainTicket.Models;
using TrainTicket.ViewModels;

namespace TrainTicket.Controllers
{
    public class TicketController : Controller
    {
        private readonly DataContext _context;


        public TicketController(DataContext context)
        {
            _context = context;
        }
        public IActionResult Index(DateTime SearchbyDate)
        {
            if (HttpContext.Session.GetString("Email") == null)
            {
                return RedirectToAction("NotFound", "Home");

            }

            if (HttpContext.Session.GetString("UserType") == "Admin" || HttpContext.Session.GetString("UserType") == "Seller")
            {
                var AllTicInf = _context.ticketInformations.OrderByDescending(p => p.TicketID).ToList();
                var avlTickts = _context.ticketInformations.Where(x => x.TotalSit != 0 && (x.JourneyTime > DateTime.Now || x.JourneyTime == DateTime.Now)).OrderByDescending(p=>p.TicketID).ToList();
                ViewData["avlTickts"] = avlTickts;
                var expTickts = _context.ticketInformations.Where(x => x.TotalSit == 0 || x.JourneyTime < DateTime.Now).OrderByDescending(p => p.TicketID).ToList();
                ViewData["expTickts"] = expTickts;
                

                return View(AllTicInf);
            }
            return RedirectToAction("NotFound", "Home");




    }

        public IActionResult Create()
        {

            if (HttpContext.Session.GetString("Email") == null)
            {
                return RedirectToAction("NotFound", "Home");
            }
            if (HttpContext.Session.GetString("UserType") == "Admin" || HttpContext.Session.GetString("UserType") == "Seller")
            {
                loadDDL();

                return View();
            }
            return RedirectToAction("NotFound", "Home");
        }
        [HttpPost]
        public IActionResult Create(TicketInformation ticketInformations)
        {
            if(_context.ticketInformations.Count() != 0)
            {
                var totaltickets = _context.ticketInformations.OrderByDescending(p=>p.TicketID).FirstOrDefault().TotalTicketsAllTime;
                var userid = Convert.ToInt32(HttpContext.Session.GetString("UserID"));
                TicketInformation ticket = new TicketInformation
                {
                    TrainName = ticketInformations.TrainName,
                    JourneyTime = ticketInformations.JourneyTime,
                    PerTicketPrice = ticketInformations.PerTicketPrice,
                    TotalSit = ticketInformations.TotalSit,
                    FStarionName = ticketInformations.FStarionName,
                    TStationName = ticketInformations.TStationName,
                    SitClass = ticketInformations.SitClass,
                    SellerID = userid,
                    TotalTicketsAllTime = (ticketInformations.TotalSit + totaltickets)
                };
                _context.Add(ticket);
                _context.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            else
            {
                var totaltickets = 0;
                var userid = Convert.ToInt32(HttpContext.Session.GetString("UserID"));
                TicketInformation ticket = new TicketInformation
                {
                    TrainName = ticketInformations.TrainName,
                    JourneyTime = ticketInformations.JourneyTime,
                    PerTicketPrice = ticketInformations.PerTicketPrice,
                    TotalSit = ticketInformations.TotalSit,
                    FStarionName = ticketInformations.FStarionName,
                    TStationName = ticketInformations.TStationName,
                    SitClass = ticketInformations.SitClass,
                    SellerID = userid,
                    TotalTicketsAllTime = (ticketInformations.TotalSit + totaltickets)
                };
                _context.Add(ticket);
                _context.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            return View();
            
            
        }












        private void loadDDL()
        {
           
                List<Station> stations = new List<Station>();
                stations = _context.stations.ToList();
                List<Train> trains = new List<Train>();
                trains = _context.trains.ToList();

                ViewBag.TrainName = trains;
                ViewBag.StationName = stations;
           
        }
        
        


     }
}

TrainTicket/Controllers/TrainsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TrainTicket.Data;
using TrainTicket.Models;

namespace TrainTicket.Controllers
{
    public class TrainsController : Controller
    {
        private readonly DataContext _context;


        public TrainsController(DataContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("Email") == null)
            {
                return RedirectToAction("NotFound", "Home");
                
            }
            if (HttpContext.Session.GetString("UserType") == "Admin" || HttpContext.Session.GetString("UserType") == "Seller")
            {
                var totaltrain = _context.trains.Count();
                ViewBag.totaltrain = totaltrain;
                var trains = _context.trains.ToList();
                return View(trains);
            }
            return RedirectToAction("NotFound", "Home");
        }
        public IActionResult Create()
        {
            if (HttpContext.Session.GetString("Email") == null)
            {
                return RedirectToAction("NotFound", "Home");
                
            }
            if (HttpContext.Session.GetString("UserType") == "Admin" || HttpContext.Session.GetString("UserType") == "Seller")
            {
                return View();
            }
            return RedirectToAction("NotFound", "Home");
        }
        [HttpPost]
        public IActionResult Create(Train trains)
        {
            _context.Add(trains);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

    }
}

TrainTicket/Controllers/UsertypeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TrainTicket.Data;
using TrainTicket.Models;

namespace TrainTicket.Controllers
{
    public class UsertypeController : Controller
    {
        private readonly DataContext _context;


        public UsertypeController(DataContext context)
        {
            _context = context;
        }


        public IActionResult Index()
        {
            var usertype = _context.userTypes.ToList();
            return View(usertype);
        }

        public IActionResult Create()
        {
            
            return View();
        }
        [HttpPost]
        public IActionResult Create(UserType userTypes)
        {
            _context.Add(userTypes);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }











    }
}

TrainTicket/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TrainTicket</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />*@






    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/Assets/plugins/fontawesome-free/css/all.min.css">
    <!-- DataTables -->
    <link rel="stylesheet" href="~/Assets/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/Assets/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="~/Assets/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Assets/dist/css/adminlte.min.css">







</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TrainTicket</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ticket" asp-action="Index">Tickets</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Stations" asp-action="Index">Stations</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Trains" asp-action="Index">Trains</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usertype" asp-action="Index">User Type</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - TrainTicket - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>






    <!-- jQuery -->
    <script src="~/Assets/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/Assets/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- DataTables  & Plugins -->
    <script src="~/Assets/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/Assets/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/Assets/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/Assets/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script src="~/Assets/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
    <script src="~/Assets/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
    <script src="~/Assets/plugins/jszip/jszip.min.js"></script>
    <script src="~/Assets/plugins/pdfmake/pdfmake.min.js"></script>
    <script src="~/Assets/plugins/pdfmake/vfs_fonts.js"></script>
    <script src="~/Assets/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
    <script src="~/Assets/plugins/datatables-buttons/js/buttons.print.min.js"></script>
    <script src="~/Assets/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/Assets/dist/js/adminlte.min.js"></script>





    @RenderSection("Scripts", required: false)
</body>
</html>